project:
  type: default
  render:
    - case-kjernekraft/nytte_kjernekraft.md
    - case-kjernekraft/case-kjernekraft.qmd
    - forelesninger/Forelesning4.qmd
    - forelesninger/Forelesning7.qmd
    - forelesninger/Forelesning8.qmd

  


format:
  pdf: default
  ipynb: default
  html:
    include-before-body: _includes/inject-navbar.html
