project:
  type: default
  render:

    - Forelesning 4.qmd
    - Forelesning 7.qmd
    - Forelesning 8.qmd
    - case-kjernekraft.qmd
  


format:
  pdf: default
  ipynb: default
  html: default
